name: 发布 Docker 镜像 (amd64)

on:
  push:
    tags:
      - '*'
      - '!*-alpha*'
  workflow_dispatch:
    inputs:
      version:
        description: '输入版本号'
        required: true

jobs:
  push_to_registries:
    name: 推送 Docker 镜像到多个注册表
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v2

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 登录到 Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 登录到容器注册表
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 保存版本信息
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            VERSION=$(git describe --tags)
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
          fi

      - name: 提取 Docker 的元数据（标签、标签）
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            jonathanfanee/chatapi365
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=tag
            ${{ env.VERSION }}

      - name: 缓存 Docker 层
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: 构建并推送 Docker 镜像
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
